Search.appendIndex(
    [
                {
            "fqsen": "\\Connexion",
            "name": "Connexion",
            "summary": "Connexion\u0020\u003A\u0020Connexion\u0020et\u0020communication\u0020avec\u0020la\u0020BDD",
            "url": "classes/Connexion.html"
        },                {
            "fqsen": "\\Connexion\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "__construct",
            "url": "classes/Connexion.html#method___construct"
        },                {
            "fqsen": "\\Connexion\u003A\u003ArecupISBN\u0028\u0029",
            "name": "recupISBN",
            "summary": "recupISBN",
            "url": "classes/Connexion.html#method_recupISBN"
        },                {
            "fqsen": "\\Connexion\u003A\u003AafficherExemplaire\u0028\u0029",
            "name": "afficherExemplaire",
            "summary": "afficherExemplaire",
            "url": "classes/Connexion.html#method_afficherExemplaire"
        },                {
            "fqsen": "\\Connexion\u003A\u003AtitreLivre\u0028\u0029",
            "name": "titreLivre",
            "summary": "titreLivre",
            "url": "classes/Connexion.html#method_titreLivre"
        },                {
            "fqsen": "\\Connexion\u003A\u003A\u0024bdd",
            "name": "bdd",
            "summary": "",
            "url": "classes/Connexion.html#property_bdd"
        },                {
            "fqsen": "\\Exemplaire",
            "name": "Exemplaire",
            "summary": "Exemplaire\u0020\u003A\u0020Class\u0020des\u0020exemplaire",
            "url": "classes/Exemplaire.html"
        },                {
            "fqsen": "\\Exemplaire\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "__construct",
            "url": "classes/Exemplaire.html#method___construct"
        },                {
            "fqsen": "\\Exemplaire\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Exemplaire.html#property_id"
        },                {
            "fqsen": "\\Exemplaire\u003A\u003A\u0024idUtilisateur",
            "name": "idUtilisateur",
            "summary": "",
            "url": "classes/Exemplaire.html#property_idUtilisateur"
        },                {
            "fqsen": "\\Exemplaire\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/Exemplaire.html#property_status"
        },                {
            "fqsen": "\\Livre",
            "name": "Livre",
            "summary": "Livre\u0020\u003A\u0020Class\u0020des\u0020livre",
            "url": "classes/Livre.html"
        },                {
            "fqsen": "\\Livre\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "__construct",
            "url": "classes/Livre.html#method___construct"
        },                {
            "fqsen": "\\Livre\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "jsonSerialize",
            "url": "classes/Livre.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024isbn",
            "name": "isbn",
            "summary": "",
            "url": "classes/Livre.html#property_isbn"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024titre",
            "name": "titre",
            "summary": "",
            "url": "classes/Livre.html#property_titre"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024nom",
            "name": "nom",
            "summary": "",
            "url": "classes/Livre.html#property_nom"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024prenom",
            "name": "prenom",
            "summary": "",
            "url": "classes/Livre.html#property_prenom"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024editeur",
            "name": "editeur",
            "summary": "",
            "url": "classes/Livre.html#property_editeur"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024format",
            "name": "format",
            "summary": "",
            "url": "classes/Livre.html#property_format"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024section",
            "name": "section",
            "summary": "",
            "url": "classes/Livre.html#property_section"
        },                {
            "fqsen": "\\Livre\u003A\u003A\u0024categorie",
            "name": "categorie",
            "summary": "",
            "url": "classes/Livre.html#property_categorie"
        },                {
            "fqsen": "\\Utilisateur",
            "name": "Utilisateur",
            "summary": "Utilisateur\u0020\u003A\u0020Class\u0020utilisateur",
            "url": "classes/Utilisateur.html"
        },                {
            "fqsen": "\\Utilisateur\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "__construct",
            "url": "classes/Utilisateur.html#method___construct"
        },                {
            "fqsen": "\\Utilisateur\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "jsonSerialize",
            "url": "classes/Utilisateur.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Utilisateur\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Utilisateur.html#property_id"
        },                {
            "fqsen": "\\Utilisateur\u003A\u003A\u0024nom",
            "name": "nom",
            "summary": "",
            "url": "classes/Utilisateur.html#property_nom"
        },                {
            "fqsen": "\\Utilisateur\u003A\u003A\u0024prenom",
            "name": "prenom",
            "summary": "",
            "url": "classes/Utilisateur.html#property_prenom"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
